name: Deploy

on:
  # Trigger the workflow on push to master
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: macOS-11
    env:
      VERSION: 1.0.2
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Get Latest Version & Build Number
      uses: yanamura/ios-bump-version@v1
      with:
        build-number: ${{ github.run_number }}
        version: ${{ env.VERSION }}
    - name: Install GPG
      run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Handle provisioning
      run: ./provisioning/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.provisioning_password }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: |
        xcodebuild \
          -sdk iphoneos \
          -project Busyless.xcodeproj \
          -configuration Release \
          -scheme Busyless \
          -derivedDataPath DerivedData \
          -archivePath DerivedData/Archive/Busyless \
          archive
    - name: Export Archive
      run: |
        xcodebuild \
          -exportArchive \
          -archivePath DerivedData/Archive/Busyless.xcarchive \
          -exportOptionsPlist provisioning/App-Store.plist \
          -exportPath DerivedData/ipa
    - name: Dump file hierarchy
      run: ls -R
    - name: Deploy App to Apple
      run: |
        xcrun altool \
          --upload-app \
          --type ios \
          --file DerivedData/ipa/Busyless.ipa \
          --username "${{ secrets.appstore_connect_username }}" \
          --password "${{ secrets.appstore_connect_password }}" --verbose
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ env.VERSION }}-${{ github.run_number }}
