name: Deploy

on:
  # Trigger the workflow on push to master
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get latest version and build number
      uses: yanamura/ios-bump-version@v1
      with:
        version: 0.0.1
        build-number: ''
    - name: Update version and build number
      run: |
        git add .
        git commit -m "AUTOMATIC VERSION BUMP"
        git push origin HEAD
    - name: Install GPG
      run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Handle provisioning
      run: ./provisioning/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.provisioning_password }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: xcodebuild \
        -sdk iphoneos \
        -project TimeBudget.xcodeproj \
        -configuration Release \
        -scheme TimeBudget \
        -derivedDataPath DerivedData \
        -archivePath DerivedData/Archive/TimeBudget \
        archive
    - name: Export Archive
      run: xcodebuild \
        -exportArchive \
        -archivePath DerivedData/Archive/TimeBudget.xcarchive \
        -exportOptionsPlist provisioning/App-Store.plist \
        -exportPath DerivedData/ipa
    - name: Dump file hierarchy
      run: ls -R
    - name: Deploy App to Apple
      run: xcrun altool \
        --upload-app \
        --type ios \
        --file DerivedData/ipa/TimeBudget.ipa \
        --username "${{ secrets.appstore_connect_username }}" \
        --password "${{ secrets.appstore_connect_password }}" --verbose