name: Deploy

on:
  # Trigger the workflow on push to master
  push:
    branches:
      - master
    paths-ignore:
      - '**/project.pbxproj'
      - '**/Info.plist'
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN_ACTION }}
    - name: Get Latest Version & Build Number
      uses: yanamura/ios-bump-version@v1
      with:
        version: 0.0.2
    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        author_name: Auto Committer
        author_email: automatic@version.bump
        force: true
        message: 'AUTOMATIC VERSION BUMP'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install GPG
      run: brew install gnupg
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Handle provisioning
      run: ./provisioning/import_provisioning.sh
      env:
        PROVISIONING_PASSWORD: ${{ secrets.provisioning_password }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app && /usr/bin/xcodebuild -version
    - name: Build archive
      run: |
        xcodebuild \
          -sdk iphoneos \
          -project Busyless.xcodeproj \
          -configuration Release \
          -scheme Busyless \
          -derivedDataPath DerivedData \
          -archivePath DerivedData/Archive/Busyless \
          archive
    - name: Export Archive
      run: |
        xcodebuild \
          -exportArchive \
          -archivePath DerivedData/Archive/Busyless.xcarchive \
          -exportOptionsPlist provisioning/App-Store.plist \
          -exportPath DerivedData/ipa
    - name: Dump file hierarchy
      run: ls -R
    - name: Deploy App to Apple
      run: |
        xcrun altool \
          --upload-app \
          --type ios \
          --file DerivedData/ipa/Busyless.ipa \
          --username "${{ secrets.appstore_connect_username }}" \
          --password "${{ secrets.appstore_connect_password }}" --verbose
